import os
import sys
from pathlib import Path

import pytest


TEST_ENV = {
    "SERVER_HOST": "127.0.0.1",
    "SERVER_PORT": "21063",
    "SERVER_BASE_URL": "http://127.0.0.1:21063",
    "ROBOT_ID": "pi-01",
    "SESSION_SECRET_KEY": "test-session-secret",
    "COOKIE_SECURE": "false",
    "ROBOT_CONTROL_TOKEN": "test-robot-token",
    "EMAIL_VERIFICATION_SECRET": "test-email-secret",
    "EMAIL_VERIFICATION_TTL_SEC": "600",
    "EMAIL_VERIFICATION_RESEND_COOLDOWN_SEC": "60",
    "EMAIL_VERIFICATION_MAX_ATTEMPTS": "5",
    "EMAIL_VERIFICATION_MAX_SENDS": "5",
    "LOGIN_MAX_FAILURES": "10",
    "LOGIN_LOCKOUT_SEC": "600",
    "DB_HOST": "127.0.0.1",
    "DB_PORT": "3306",
    "DB_NAME": "test_dabom",
    "DB_USER": "test_user",
    "DB_PASSWORD": "test_password",
    "DB_CONNECT_TIMEOUT_SEC": "5",
    "SMTP_HOST": "",
    "SMTP_PORT": "587",
    "SMTP_USERNAME": "",
    "SMTP_PASSWORD": "",
    "SMTP_FROM_EMAIL": "",
    "SMTP_FROM_NAME": "Dabom test",
    "SMTP_USE_TLS": "true",
    "SMTP_USE_SSL": "false",
    "SMTP_TIMEOUT_SEC": "10",
    "TELEGRAM_TOKEN": "",
    "TELEGRAM_CHAT_ID": "",
    "TELEGRAM_ALERT_COOLDOWN_SEC": "10",
    "STREAM_WIDTH": "640",
    "STREAM_HEIGHT": "480",
    "STREAM_FPS": "15",
    "STREAM_BITRATE": "1000000",
    "STREAM_INFER": "false",
    "STREAM_RETRY_SEC": "3",
    "STREAM_JPEG_QUALITY": "70",
    "PREVIEW_MAX_FPS": "10",
    "CURL_CONNECT_TIMEOUT_SEC": "5",
    "CAMERA_TIMEOUT_SEC": "3",
    "ROBOT_STATUS_TIMEOUT_SEC": "5",
    "PIPELINE": "1",
    "MODEL_REQUIRED": "false",
    "INFERENCE_ENABLED": "false",
    "VISUALIZATION_ENABLED": "false",
    "INFERENCE_MAX_FPS": "10",
    "STREAM_INFER_EVERY_N": "1",
    "ADAPTIVE_BATCHING_ENABLED": "true",
    "ADAPTIVE_BATCH_MAX_WAIT_MS": "8",
    "ACTION_SUSPICIOUS_THRESHOLD": "0.20",
    "ACTION_DANGER_THRESHOLD": "0.50",
    "ACTION_DISPLAY_TTL_SEC": "1",
    "TRIGGER_SUSPICIOUS_VISUAL_ENABLED": "true",
    "INFERENCE_MAX_RESULT_AGE_SEC": "3",
    "INFERENCE_DROP_OLDER_THAN_SEC": "2",
    "CUDA_DEVICE_INDEX": "0",
    "DEVICE": "cuda:0",
    "GPU_REQUIRED_FOR_INFERENCE": "true",
    "ENV_RELOAD_CHECK_INTERVAL_SEC": "1",
    "SAVE_RECEIVED_FRAMES": "false",
    "VIOLENCE_HEURISTIC_ENABLED": "true",
    "VIOLENCE_HEURISTIC_HISTORY_FRAMES": "12",
    "VIOLENCE_HEURISTIC_SUSPICIOUS_FRAMES": "3",
    "VIOLENCE_HEURISTIC_DANGER_FRAMES": "4",
    "VIOLENCE_HEURISTIC_MOTION_THRESHOLD": "0.07",
    "VIOLENCE_HEURISTIC_APPROACH_THRESHOLD": "0.035",
    "VIOLENCE_HEURISTIC_PROXIMITY_THRESHOLD": "0.36",
    "VIOLENCE_HEURISTIC_PAIR_DISTANCE_THRESHOLD": "1.45",
    "VIOLENCE_HEURISTIC_SUSPICIOUS_SCORE": "0.34",
    "VIOLENCE_HEURISTIC_DANGER_SCORE": "0.48",
    "VIOLENCE_HEURISTIC_USE_LEG_STRIKES": "false",
    "VIOLENCE_HEURISTIC_USE_BOX_TARGET_POINTS": "false",
    "MOTOR_OUTPUT_ENABLED": "false",
    "MOTOR_SERIAL_PORT": "test-serial",
    "MOTOR_SERIAL_BAUDRATE": "115200",
    "MOTOR_SERIAL_TIMEOUT_SEC": "0.25",
    "MAX_WHEEL_MPS": "0.50",
    "MIN_AUTO_DRIVE_PWM": "0.30",
    "COMMAND_TIMEOUT_SEC": "0.45",
    "STATUS_INTERVAL_SEC": "1",
    "STATUS_REQUEST_TIMEOUT_SEC": "1",
    "WS_RECONNECT_DELAY_SEC": "1",
    "ENCODER_INTERVAL_SEC": "0.05",
    "ROBOT_COMMAND_ACK_TIMEOUT_SEC": "2",
    "ROS_DOMAIN_ID": "27",
    "ROS_LOCALHOST_ONLY": "1",
    "LIDAR_ENABLE": "false",
    "LIDAR_ROS_TOPIC": "/scan",
    "LIDAR_SCAN_TOPIC": "/scan",
    "LIDAR_BASE_FRAME": "base_link",
    "LIDAR_FRAME": "laser",
    "LIDAR_X": "0",
    "LIDAR_Y": "0",
    "LIDAR_Z": "0.12",
    "LIDAR_ROLL": "0",
    "LIDAR_PITCH": "0",
    "LIDAR_YAW": "0",
    "LIDAR_DASHBOARD_MAX_POINTS": "360",
    "LIDAR_USE_SOURCE_TIMESTAMP": "true",
    "LIDAR_WS_RECONNECT_SEC": "1",
    "LIDAR_SERIAL_PORT": "test-lidar",
    "LIDAR_SERIAL_BAUDRATE": "115200",
    "LIDAR_DRIVER_PACKAGE": "test_lidar_driver",
    "LIDAR_DRIVER_EXECUTABLE": "test_lidar_node",
    "ENCODER_ROS_ENABLE": "false",
    "ENCODER_ROS_TOPIC": "/wheel_ticks",
    "WHEEL_DIAMETER_M": "0.0675",
    "WHEEL_TRACK_M": "0.201",
    "ENCODER_TICKS_PER_REV": "14289.848",
    "WHEEL_TICKS_TOPIC": "/wheel_ticks",
    "ODOM_TOPIC": "/odom",
    "ODOM_FRAME": "odom",
    "BASE_FRAME": "base_link",
    "ODOMETRY_ENCODER_TIMEOUT_SEC": "0.25",
    "NAV_DRY_RUN_ENABLED": "true",
    "NAVIGATION_TIMEOUT_SEC": "5",
    "NAVIGATION_DEFAULT_MODE": "MAPPING",
    "NAV_SCAN_TIMEOUT_SEC": "1.5",
    "NAV_STOP_DISTANCE_M": "0.35",
    "NAV_SLOW_DISTANCE_M": "0.70",
    "NAV_NORMAL_LINEAR_MPS": "0.20",
    "NAV_SLOW_LINEAR_MPS": "0.08",
    "NAV_TURN_ANGULAR_RPS": "0.45",
    "NAV_PROCESS_START_TIMEOUT_SEC": "1",
    "NAV_PROCESS_STOP_TIMEOUT_SEC": "2",
    "NAV_DRIVING_READY_TIMEOUT_SEC": "15",
    "NAV_COMPUTE_PATH_TIMEOUT_SEC": "10",
    "NAV_CANCEL_TIMEOUT_SEC": "3",
    "NAV_CANCEL_RESULT_TIMEOUT_SEC": "3",
    "NAV_WATCHDOG_INTERVAL_SEC": "0.25",
    "NAV_WATCHDOG_LIDAR_TIMEOUT_SEC": "1.5",
    "NAV_WATCHDOG_ODOM_TIMEOUT_SEC": "1",
    "NAV_WATCHDOG_TF_TIMEOUT_SEC": "1",
    "NAV_WATCHDOG_TF_SOURCE_MAX_AGE_SEC": "1",
    "NAV_WATCHDOG_LOCALIZATION_TIMEOUT_SEC": "2",
    "NAV_WATCHDOG_PI_TIMEOUT_SEC": "3",
    "NAV_WATCHDOG_STOP_ENCODER_GRACE_SEC": "0.35",
    "NAV_WATCHDOG_STOP_ENCODER_TICKS": "4",
    "SYSTEM_STATUS_INTERVAL_SEC": "5",
    "EVENT_SAVE_COOLDOWN_SEC": "10",
}

os.environ.update(TEST_ENV)


@pytest.fixture(autouse=True)
def isolate_runtime_env_file(monkeypatch, tmp_path_factory):
    app_module = sys.modules.get("server.app")
    if app_module is not None:
        runtime_env = tmp_path_factory.mktemp("runtime-env") / "runtime.env"
        runtime_env.write_text(
            "\n".join(
                f"{key}={TEST_ENV[key]}"
                for key in app_module.RUNTIME_MODEL_ENV_KEYS
            ),
            encoding="utf-8",
        )
        monkeypatch.setattr(app_module, "ENV_PATH", runtime_env)
